services:
  server:
    container_name: z37_projekt_server
    hostname: z37_projekt_server
    build: ./server
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      - z37_network
  
  client:
    #container_name: z37_projekt_client
     #hostname: z37_projekt_client
    build: ./client
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      - z37_network
    depends_on:
      - server

networks:
  z37_network:
    external: true

